package com.yoyuapp.sqlbuilder;

import java.util.Calendar;

public class Member {
	private int id;
	private String name;
	private String age;
	private Calendar registerTime;
	
	//... gets and sets here...
	
	
	/***** code follows could be generated by some code generator *****/
	
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getAge() {
		return age;
	}
	public void setAge(String age) {
		this.age = age;
	}
	public Calendar getRegisterTime() {
		return registerTime;
	}
	public void setRegisterTime(Calendar registerTime) {
		this.registerTime = registerTime;
	}
	
	
	
}
