package com.yoyuapp.sqlbuilder;

import java.math.BigDecimal;
import java.util.Calendar;

import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name="order")
public class Order {
	private int id;
	private String name;
	private int memberId;
	private BigDecimal amount;
	private Calendar createTime;
	
	//... gets and sets here...
	
	
	/***** code follows could be generated by some code generator *****/
	
	//table
	public static SqlTable _TABLE = SqlTable.of("order");
	
	//each column
	public static SqlColumn _ALL 			= SqlColumn.of(_TABLE, "*");
	public static SqlColumn ID 				= SqlColumn.of(_TABLE, "id");
	public static SqlColumn MEMBER_ID		= SqlColumn.of(_TABLE, "memberId");
	public static SqlColumn NAME 			= SqlColumn.of(_TABLE, "name");
	public static SqlColumn AMOUNT 			= SqlColumn.of(_TABLE, "amount");
	public static SqlColumn CREATE_TIME 	= SqlColumn.of(_TABLE, "createTime");
	
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public BigDecimal getAmount() {
		return amount;
	}
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	public Calendar getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Calendar createTime) {
		this.createTime = createTime;
	}
	public int getMemberId() {
		return memberId;
	}
	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}
	
	
}
